const {test,expect}=require('@playwright/test');
const {DatabaseSync}=require('node:sqlite');
const fs=require('node:fs/promises');
const domain=require('../scripts/billing-domain.js');
const url='/44.billing_overview.html';
let bills;
test.beforeEach(async({page})=>{
 const filename=process.env.BILLING_DB_PATH;if(!filename?.includes('paywizard-billing-e2e-'))throw new Error('An isolated billing test database is required.');
 const db=new DatabaseSync(filename);db.exec('DELETE FROM bills');const now=new Date();bills=[];
 for(let i=0;i<25;i++){
  const b=domain.makeBill({id:'overview-'+i,merchantId:'M-123',merchantName:'Existing Shop',invoice:'OV-'+i,currency:'USD',amount:24,recurring:i!==0,cycle:3,start:i===1?'2020-01-01':'2099-01-31',expiry:i===0?'2020-01-01':'2099-12-31',notes:i===0?'=1+1':'Platform service',createdAt:new Date(now.getTime()-i*60000).toISOString()},now);
  if(i===1)domain.checkout(b,{requestId:crypto.randomUUID(),email:'payer@example.com',brand:'Visa',last4:'4242',acceptedTerms:true,recurringConsent:true},now,{failAt:1});
  bills.push(b);db.prepare('INSERT INTO bills(id,token,document) VALUES(?,?,?)').run(b.id,b.linkToken,JSON.stringify(b));
 }
 db.close();await page.addInitScript(()=>{if(!localStorage.getItem('paywizard.portalAccessProfile.v1'))localStorage.setItem('paywizard.portalAccessProfile.v1','wizarpos');localStorage.setItem('paywizard-platform-merchants-v1',JSON.stringify([{merchantId:'M-123',merchantName:'Existing Shop'}]));});
});
for(const width of [1440,390])test('renew, same URL, stop and audit in shared overview at '+width,async({page,context})=>{
 await page.setViewportSize({width,height:960});await page.goto(url);await expect(page.locator('#pageSummary')).toHaveText('1 / 2 (25)');const row=page.locator('[data-id="overview-0"]');
 await row.locator('.billing-more').click();const link=await page.getByRole('menuitem',{name:'Preview payment link'}).getAttribute('href');const payer=await context.newPage();await payer.goto(new URL('/43.billing_payment_link.html#'+bills[0].linkToken,page.url()).href);await expect(payer.locator('#pageError')).toContainText('expired');
 await page.getByRole('menuitem',{name:'Renew Link',exact:true}).click();expect(await page.locator('#renewDialog button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).toEqual([40,40,40]);await page.getByRole('button',{name:'Renew & Send Link',exact:true}).click();await expect(page.locator('#renewError')).toContainText('recipient');await page.locator('#renewRecipient').fill('payer@example.com');await page.getByRole('button',{name:'Renew & Send Link',exact:true}).click();await expect(page.locator('#renewDialog')).toBeHidden();
 await row.locator('.billing-more').click();await expect(page.getByRole('menuitem',{name:'Preview payment link'})).toHaveAttribute('href',link);await page.getByRole('menuitem',{name:'View billing details',exact:true}).click();await expect(page.locator('#billingAudit')).toContainText('Renew Link');await expect(page.locator('#billingAudit')).toContainText('Simulated');await page.locator('#closeBillingDetails').click();
 await payer.getByRole('button',{name:'Refresh payment link',exact:true}).click();await expect(payer.locator('#cardForm')).toBeVisible();
 await row.locator('.billing-more').click();await page.getByRole('menuitem',{name:'Stop Collection',exact:true}).click();expect(await page.locator('#stopDialog button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).toEqual([40,40]);await page.locator('#stopReason').fill('Customer request');await page.locator('#stopDialog button[type=submit]').click();await expect(row).toContainText('Stopped');await payer.reload();await expect(payer.locator('#paymentResult')).toContainText('Collection stopped');await expect(payer.locator('#cardForm')).toBeHidden();
 await row.locator('.billing-more').click();await expect(page.getByRole('menuitem',{name:'Renew Link',exact:true})).toHaveCount(0);await expect(page.getByRole('menuitem',{name:'Stop Collection',exact:true})).toHaveCount(0);await page.getByRole('menuitem',{name:'View billing details',exact:true}).click();await expect(page.locator('#savedBillingDetails')).toContainText('Customer request');await page.locator('#closeBillingDetails').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await payer.close();
});
test('filters, pagination, reset, CSV export and menu keyboard dismissal',async({page})=>{
 await page.goto(url);await expect(page.locator('#pageSummary')).toHaveText('1 / 2 (25)');await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.locator('#pageSummary')).toHaveText('2 / 2 (25)');await page.locator('#overviewStatus').selectOption('Overdue');await page.getByRole('button',{name:'Search billing overview'}).click();await expect(page.locator('#overviewRows tr')).toHaveCount(1);await expect(page.locator('#overviewRows')).toContainText('OV-1');await page.getByRole('button',{name:'Reset filters'}).click();
 await page.locator('#overviewMerchant').fill('missing');await page.getByRole('button',{name:'Search billing overview'}).click();await expect(page.locator('#overviewRows')).toContainText('No billing records found.');await expect(page.locator('#exportOverview')).toBeDisabled();await page.getByRole('button',{name:'Reset filters'}).click();
 const downloadEvent=page.waitForEvent('download');await page.locator('#exportOverview').click();const download=await downloadEvent;const csv=await fs.readFile(await download.path(),'utf8');expect(csv).toContain("\"'=1+1\"");expect(csv.split('\r\n')).toHaveLength(26);
 await page.locator('[data-id="overview-0"] .billing-more').click();await page.getByRole('menuitem',{name:'Preview payment link'}).press('End');await expect(page.getByRole('menuitem',{name:'Stop Collection',exact:true})).toBeFocused();await page.getByRole('menuitem',{name:'Stop Collection',exact:true}).press('Escape');await expect(page.locator('#overviewMenu')).toBeHidden();await expect(page.locator('[data-id="overview-0"] .billing-more')).toBeFocused();
});
test('failed first charge uses payer retry, payment records show separate attempts',async({page,context})=>{
 await page.goto(url);await expect(page.locator('[data-id="overview-1"]')).toContainText('Overdue');const payer=await context.newPage();await payer.goto(new URL('/43.billing_payment_link.html#'+bills[1].linkToken,page.url()).href);await expect(payer.locator('#cardForm')).toBeHidden();await payer.getByRole('button',{name:'Retry Payment',exact:true}).click();await expect(payer.locator('#retryPaymentSummary')).toContainText('3 installments · Total $72.00');await payer.locator('.retry-confirm input').check();await payer.locator('.billing-retry-dialog button[type=submit]').click();await expect(payer.locator('#paymentResult')).toContainText('3 of 3 installments paid.');await expect(payer.locator('#retryPayment')).toHaveCount(0);await page.reload();const row=page.locator('[data-id="overview-1"]');await expect(row).toContainText('Paid');await row.locator('.billing-more').click();await page.getByRole('menuitem',{name:'View payment records',exact:true}).click();await expect(page.locator('#attemptRows tr')).toHaveCount(4);await expect(page.locator('#installmentRows tr')).toHaveCount(3);await payer.close();
});
test('merchant retry has the same confirmation and own-bill boundary',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('paywizard.portalAccessProfile.v1','billing-merchant'));await page.goto('/42.billing_payments.html?merchantId=M-123');await page.getByRole('button',{name:'Retry Payment',exact:true}).click();await expect(page.locator('#retryPaymentSummary')).toContainText('Total $72.00');await page.locator('.retry-confirm input').check();await page.locator('.billing-retry-dialog button[type=submit]').click();await expect(page.getByRole('button',{name:'Retry Payment',exact:true})).toHaveCount(0);await page.locator('#historyTab').click();await expect(page.locator('#paymentHistoryRows tr').filter({has:page.getByRole('cell',{name:'OV-1',exact:true})})).toContainText('Paid');
});
test('overview menu, direct route and role switching enforce provider profile',async({page})=>{
 await page.goto(url);await expect(page.getByRole('heading',{name:'Billing Overview',exact:true})).toBeVisible();
 for(const profile of ['Full-Service Provider','Attended Provider','Unattended Provider','Attended Merchant','Unattended Merchant','Attended Store','Unattended Store','Billing-only Merchant']){
  await page.getByLabel('Change portal access profile').click();await page.getByRole('menuitemradio',{name:profile,exact:true}).click();await expect(page).not.toHaveURL(/44\.billing_overview/);await expect(page.getByRole('link',{name:'Billing Overview',exact:true})).toHaveCount(0);await page.goto(url);await expect(page).not.toHaveURL(/44\.billing_overview/);await page.getByLabel('Change portal access profile').click();await page.getByRole('menuitemradio',{name:'WizarPOS Provider',exact:true}).click();await page.goto(url);await expect(page.getByRole('heading',{name:'Billing Overview',exact:true})).toBeVisible();
 }
});
