const {test,expect}=require('@playwright/test');
for(const width of [1440,390])test('local only, expired examples and stable renewal at '+width,async({page,context})=>{
 await page.setViewportSize({width,height:950});
 await page.addInitScript(()=>localStorage.setItem('paywizard-billing-runtime-v1',JSON.stringify({mode:'shared',origin:'https://unavailable.example'})));
 const requests=[];page.on('request',r=>{if(r.url().includes('/api/billing/'))requests.push(r.url());});
 await page.goto('/44.billing_overview.html');
 await expect(page.locator('.billing-runtime')).toHaveCount(0);
 await expect(page.locator('#overviewRows tr').first()).toContainText('RENEW-0001');
 const row=page.locator('#overviewRows tr').filter({has:page.getByRole('cell',{name:'RENEW-0001',exact:true})});
 const url=await page.evaluate(()=>{const s=window.PaywizardBillingStore;return s.link(s.read().find(r=>r.invoice==='RENEW-0001'));});
 const payer=await context.newPage();await payer.goto(url);await expect(payer.locator('#pageError')).toContainText('expired');
 await row.getByRole('button',{name:'Renew Link',exact:true}).click();
 const heights=await page.locator('#renewDialog .billing-actions button').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().height));expect(new Set(heights).size).toBe(1);
 await page.getByRole('button',{name:'Renew',exact:true}).click();
 await expect(row.getByRole('button',{name:'Copy URL',exact:true})).toBeVisible();
 await payer.reload();await expect(payer.locator('#cardForm')).toBeVisible();
 await page.reload();await expect(row.getByRole('button',{name:'Copy URL',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>{const s=window.PaywizardBillingStore;return s.link(s.read().find(r=>r.invoice==='RENEW-0001'));})).toBe(url);
 expect(await page.evaluate(()=>window.PaywizardBillingStore.read().filter(r=>r.invoice.startsWith('RENEW-')).length)).toBe(3);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(requests).toEqual([]);
 await row.getByRole('button',{name:'Actions for invoice RENEW-0001'}).click();
 await page.getByRole('menuitem',{name:'Stop Collection',exact:true}).click();
 await expect(page.locator('#stopDialog textarea')).toHaveCount(0);
 const stopHeights=await page.locator('#stopDialog .billing-actions button').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().height));expect(new Set(stopHeights).size).toBe(1);
 await page.locator('#stopDialog').getByRole('button',{name:'Stop Collection',exact:true}).click();await expect(row).toContainText('Stopped');
 await row.getByRole('button',{name:'Actions for invoice RENEW-0001'}).click();await page.getByRole('menuitem',{name:'View billing details'}).click();
 await expect(page.locator('#billingDetailsDialog')).not.toContainText('Activity');await expect(page.locator('#billingDetailsDialog')).not.toContainText('Stop reason');
 await page.locator('#billingDetailsDialog').getByRole('button',{name:'Close'}).click();
 const create=page.getByRole('link',{name:'Create Billing',exact:true});await expect(create).toHaveCSS('background-color','rgb(17, 17, 17)');
 expect(await create.evaluate(n=>n.getBoundingClientRect().height)).toBe(await page.getByRole('button',{name:'Export',exact:true}).evaluate(n=>n.getBoundingClientRect().height));
 await page.screenshot({path:'artifacts/billing-local-'+width+'.png',fullPage:false});
});
