const {test,expect}=require('@playwright/test');
const {DatabaseSync}=require('node:sqlite');
const setup='/41.billing_setup.html',overview='/44.billing_overview.html';
test.beforeEach(async({page})=>{
 const file=process.env.BILLING_DB_PATH;if(!file?.includes('paywizard-billing-e2e-'))throw new Error('An isolated billing test database is required.');
 const db=new DatabaseSync(file);db.exec('DELETE FROM bills');db.close();
 await page.addInitScript(()=>{localStorage.setItem('paywizard.portalAccessProfile.v1','wizarpos');localStorage.setItem('paywizard-platform-merchants-v1',JSON.stringify([{merchantId:'M-123',merchantName:'Existing Shop'}]));});
});
async function create(page,{recurring=false,standalone=false}={}){
 await page.goto(setup);if(standalone)await page.locator('[data-assignment=standalone]').click();
 await page.locator('#amount').fill('12');await page.locator('#expiry').fill('2099-12-31');
 if(recurring){await page.locator('#recurring').check();await page.locator('#startDate').fill('2099-01-31');await page.locator('#cycle').selectOption('3');}
 await page.locator('#applyBilling').click();await expect(page).toHaveURL(/44\.billing_overview\.html$/);await expect(page.locator('#overviewRows tr')).toHaveCount(1);
 return (await (await page.request.get('/api/billing/records')).json()).records[0];
}
test('draft survives reload, publishes once and leaves draft management',async({page})=>{
 await page.goto(setup);await page.locator('#recurring').check();await page.locator('#startDate').fill('2099-01-31');await page.locator('#amount').fill('12');await page.locator('#cycle').selectOption('24');await expect(page.locator('#total')).toHaveText('$288.00');await page.locator('#notes').fill('Monthly service');await page.locator('#saveDraft').click();await expect(page.locator('#billingMessage')).toHaveText('Draft saved.');
 await page.reload();await page.getByRole('tab',{name:'Drafts',exact:true}).click();await page.getByRole('button',{name:'Edit draft for Existing Shop'}).click();await expect(page.locator('#notes')).toHaveValue('Monthly service');await page.locator('#applyBilling').click();await expect(page).toHaveURL(/44\.billing_overview/);await expect(page.locator('#overviewRows')).toContainText('$288.00');await expect(page.locator('#overviewRows')).toContainText('Pending');
 await page.getByRole('link',{name:'Create Billing',exact:true}).click();await page.getByRole('tab',{name:'Drafts',exact:true}).click();await expect(page.locator('#billingRows')).toContainText('No billing records found.');
});
test('creation validation, recurring preview and tab keyboard navigation preserve form',async({page})=>{
 await page.goto(setup);await expect(page.locator('#billType option')).toHaveText(['eSIM Billing','General Billing']);await expect(page.locator('#cycle option')).toHaveCount(5);await page.locator('#applyBilling').click();await expect(page.locator('#amount')).toBeFocused();
 await page.locator('#recurring').check();await expect(page.locator('#previewDetails')).toContainText('Select date');await page.locator('#currency').selectOption('EUR');await page.locator('#amount').fill('200');await page.locator('#cycle').selectOption('3');await page.locator('#startDate').fill('2028-01-31');await expect(page.locator('#total')).toHaveText('€600.00');
 await page.locator('#notes').fill('Unsubmitted work');await page.getByRole('tab',{name:'Drafts',exact:true}).click();await page.getByRole('tab',{name:'Drafts',exact:true}).press('ArrowLeft');await expect(page.getByRole('tab',{name:'Create Billing',exact:true})).toBeFocused();await expect(page.locator('#notes')).toHaveValue('Unsubmitted work');
 await page.locator('#recurring').uncheck();await expect(page.locator('#previewDetails')).not.toContainText('Monthly amount');await expect(page.locator('#total')).toHaveText('€200.00');
});
test('eSIM allowance and standalone assignment survive draft editing and overview details',async({page})=>{
 await page.goto(setup);await page.locator('[data-assignment=standalone]').click();await page.locator('#billType').selectOption('eSIM Billing');await page.locator('#includedData').fill('1024');await page.locator('#amount').fill('12');await page.locator('#saveDraft').click();await expect(page.locator('#billingMessage')).toHaveText('Draft saved.');await page.reload();await page.getByRole('tab',{name:'Drafts',exact:true}).click();await page.getByRole('button',{name:'Edit standalone draft'}).click();await expect(page.locator('#merchant')).toBeHidden();await expect(page.locator('#includedData')).toHaveValue('1024');await page.locator('#applyBilling').click();await expect(page).toHaveURL(/44\.billing_overview/);
 await page.locator('.billing-more').click();await page.getByRole('menuitem',{name:'View billing details',exact:true}).click();await expect(page.locator('#savedBillingDetails')).toContainText('1,024 MB');await expect(page.locator('#savedBillingDetails')).toContainText('Standalone Billing');await page.locator('#closeBillingDetails').click();await expect(page.locator('.billing-more')).toBeFocused();
});
test('unavailable billing service preserves entered form and reconnects',async({page})=>{
 await page.route('**/api/billing/**',route=>route.request().url().endsWith('/config')?route.fulfill({json:{mode:'shared',configured:true}}):route.fulfill({status:503,body:'Unavailable'}));await page.goto(setup);await expect(page.locator('#retryBilling')).toBeEnabled();await page.locator('#amount').fill('25');await page.locator('#notes').fill('Keep my form');await expect(page.locator('#saveDraft')).toBeDisabled();await page.unroute('**/api/billing/**');await page.locator('#retryBilling').click();await expect(page.locator('#billingConnection')).toBeHidden();await expect(page.locator('#amount')).toHaveValue('25');await expect(page.locator('#notes')).toHaveValue('Keep my form');
});
for(const width of [1440,390])test('standalone checkout, merchant exclusion and equal operation heights at '+width,async({page,browser})=>{
 await page.setViewportSize({width,height:960});
 for(const recurring of [false,true]){
  await page.goto(setup);await page.locator('[data-assignment=standalone]').click();await page.locator('#amount').fill('12');await page.locator('#expiry').fill('2099-12-31');if(recurring){await page.locator('#recurring').check();await page.locator('#startDate').fill('2099-01-31');await page.locator('#cycle').selectOption('3');}
  expect(await page.locator('#billingForm .billing-actions button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).toEqual([40,40,40]);await page.locator('#applyBilling').click();await expect(page).toHaveURL(/44\.billing_overview/);const r=(await (await page.request.get('/api/billing/records')).json()).records[0];const row=page.locator('#overviewRows tr').filter({hasText:r.invoice});await expect(row).toContainText('Standalone Billing');await row.locator('.billing-more').click();await page.getByRole('menuitem',{name:'Send Link',exact:true}).click();expect(await page.locator('#sendLinkDialog button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).toEqual([40,40]);await page.locator('#linkRecipient').fill('payer@example.com');await page.locator('#confirmSendLink').click();await expect(page.locator('#sendLinkDialog')).toBeHidden();
  const outside=await browser.newContext({viewport:{width,height:960}});try{const checkout=await outside.newPage();await checkout.goto(new URL('/43.billing_payment_link.html#'+r.linkToken,page.url()).href);await expect(checkout.locator('#billInformation')).not.toContainText('Existing Shop');await checkout.locator('#cardEmail').fill('payer@example.com');await checkout.locator('#cardNumber').fill('4242424242424242');await checkout.locator('#cardExpiry').fill('1299');await checkout.locator('#cardCvc').fill('123');await checkout.locator('#cardholder').fill('Demo Payer');await checkout.locator('.card-agreements input').check();if(recurring)await checkout.locator('#recurringConsent').check();await checkout.locator('#submitCard').click();await expect(checkout.locator('#paymentResult')).toContainText(recurring?'1 of 3 installments paid.':'Thanks for your payment');await checkout.reload();await expect(checkout.locator('#cardForm')).toBeHidden();}finally{await outside.close();}
  await page.reload();await expect(page.locator('#overviewRows tr').filter({hasText:r.invoice})).toContainText(recurring?'Active':'Paid');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#overviewAssignment').selectOption('merchant');await page.getByRole('button',{name:'Search billing overview'}).click();await expect(page.locator('#overviewRows')).not.toContainText(r.invoice);
  const portal=await page.context().newPage();await portal.addInitScript(()=>localStorage.setItem('paywizard.portalAccessProfile.v1','billing-merchant'));await portal.goto(new URL('/42.billing_payments.html?merchantId=M-123',page.url()).href);await portal.locator('#historyTab').click();await expect(portal.locator('#paymentHistoryRows')).not.toContainText(r.invoice);await portal.evaluate(()=>localStorage.setItem('paywizard.portalAccessProfile.v1','wizarpos'));await portal.close();
 }
});
