(function () {
  'use strict';
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = (v,currency) => new Intl.NumberFormat('en-US',{style:'currency',currency}).format(v);
  const dialog = document.createElement('dialog');dialog.className='billing-retry-dialog';dialog.setAttribute('aria-labelledby','retryPaymentTitle');
  dialog.innerHTML='<form><h2 id="retryPaymentTitle">Retry Payment</h2><div id="retryPaymentSummary"></div><label class="retry-confirm"><input type="checkbox" required> I confirm the installment payments listed above using my saved card.</label><p role="alert"></p><div class="retry-actions"><button type="button">Cancel</button><button type="submit">Retry Payment</button></div></form>';
  document.body.append(dialog);let busy=false,pay=null,onComplete=null,requestId=null,record=null,opener=null;
  dialog.querySelector('button[type=button]').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>opener?.isConnected&&opener.focus());
  dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const controls=dialog.querySelectorAll('button,input');controls.forEach(b=>b.disabled=true);const error=dialog.querySelector('[role=alert]');error.textContent='';try{const result=await pay({requestId,confirmed:true,expectedInstallments:record.dueInstallments});dialog.close();onComplete(result);}catch(err){error.textContent=err.message;}finally{busy=false;controls.forEach(b=>b.disabled=false);}};
  window.PaywizardBillingRetry={open(bill,submit,done){record=bill;pay=submit;onComplete=done;requestId=crypto.randomUUID();opener=document.activeElement;dialog.querySelector('form').reset();dialog.querySelector('[role=alert]').textContent='';const due=bill.installments.filter(i=>bill.dueInstallments.includes(i.number));dialog.querySelector('#retryPaymentSummary').innerHTML='<p>Invoice '+esc(bill.invoice)+'</p><p>'+esc(bill.authorization.brand+' •••• '+bill.authorization.last4)+'</p><ul>'+due.map(i=>'<li>Installment '+esc(i.number)+' · '+esc(i.due)+' · '+esc(money(i.amount,bill.currency))+'</li>').join('')+'</ul><p><strong>'+esc(due.length+' installments · Total '+money(bill.dueAmount,bill.currency))+'</strong></p><p>Each installment is charged separately, oldest first. Payments stop if a charge fails.</p>';dialog.showModal();}};
})();
